### PR TITLE
Use fab/ for temporary scad files.

### PR DESCRIPTION
**Pull request by rrauenza**

### CODE REVIEW

**Comment by hzeller** [comment]
Can yoiu also change the STL references in the README.md ?

**Comment by hzeller** [comment]
We want to keep the 3mf files in the toplevel, because they are actually hand-made (don't worry about their file-references not working afterwards, I can hack-fix it).

We should understand 'fab' as a directory that we can entirely delete and re-create using the makefile.

**Comment by rrauenza** [comment]
gcode then, too?

**Comment by hzeller** [comment]
Yes gcode as generated file should be in fab/

**Comment by hzeller** [comment]
(I hope to have a makefile rule that take a 3mf and outputs a gcode, have not looked into invocation of prusa-slicer on the command line)

**Comment by rrauenza** [comment]
Let me try to remember how to merge those all into one change.

**Comment by hzeller** [comment]
don't worry, I can squash the pull request.

**Comment by hzeller** [comment]
Ready to merge ? I can take care of fiddling the file-references in 3mf (unfortunately, prusa-slicer does not allow to do that on the UI, but editing the file works :) ).

**Comment by rrauenza** [comment]
ok, squash it.  My rebase failed.

**Pull request merged**
