### PR TITLE
Added replicate script

### PR DESCRIPTION
**Pull request by esb7**
Script has been updated since the version last night.  It now includes separate left, right, from and back offset values and has a more reasonable output.  There are a couple of vars at the top of the python file that can add more logging or change where the temp dir is created.

The script currently has to be run by invoking python3 directly.

### CODE REVIEW

**Comment by esb7** [comment]
Looks like there are a bunch of unexpected commits.  I'm going to close this and create a new branch / pull request that hopefully looks cleaner.

**Comment by hzeller** [comment]
no worries, I can squash-merge these all to one commit.

**Comment by esb7** [comment]
I have a new branch with more changes.  Let's use that.  I'll open a PR

**Comment by hzeller** [comment]
Can you add a section in the README how to use the script, maybe with some examples ?

**Comment by hzeller** [comment]
oops, just merged this one, hopefully I now didn't create a mess for your new branch merge :/

**Comment by esb7** [comment]
Sure.  I'll look at that now.

- Eric

**Pull request merged**
