### PR TITLE
Added a shield cutting template created from the svg

### PR DESCRIPTION
**Pull request by nikkelj**
Some of us are using knives or handheld lasers to cut these.  A template is useful in that case.  Here is a template I have created from the purposes by cutting the SVG into six, sized for production on an 8x8" Ender 3.  UL, UR, ML, MR, LL, LR.

Also added an MS Visio template.  Visio does the job of splitting the SVG into 4 8.5x11" pages for us, properly scaled.

### CODE REVIEW

**Comment by nikkelj** [comment]
Ideally we could produce some PDF's for printing templates on 8.5"x11" paper as well, looking into how to do this.

**Comment by gunderson** [comment]
Would an extruded 3d-printable cutting jig that can be assembled like a jigsaw puzzle be helpful?

**Comment by nikkelj** [comment]
> Would an extruded 3d-printable cutting jig that can be assembled like a jigsaw puzzle be helpful?

I think that is a great idea!  I wound up using printed paper and assembling with scotch tape, but definitely not the most precise method...I had to tune the template a bit through the first two builds.  A puzzle jig would be more precise.

**Comment by nikkelj** [comment]
Meant to mention too...I have been beefing up the face plate connections on holes #1 and #4 with zip ties, as I found that they pop off fairly easily.  Metal tape is effective for sealing everything up.

**Comment by hzeller** [comment]
Interesting, the laser-cut shields hold on very tightly from what I have seen so far.

We should not check in STLs without the code to generate it, so that people can adjust it to their needs. Visio is not accessible to people and automating it using a Makefile is probably hard as well (not sure, never used it).

So I suggest to use the `baseline/maker-nexus-faceshield-cut.dxf` as starting point and cut out the areas using OpenSCAD and `intersection()`.

Here an example to get started
```scad
w=200;
h=300;

module baseline() {
     linear_extrude(height=0.3)
	  import("baseline/maker-nexus-faceshield-cut.dxf", convexity=10);
}

intersection() {
     baseline();
     translate([0, 0, -1]) cube([w, h, 2]);
}
```

**Comment by nikkelj** [comment]
This isn't really the occasion for me to be learning OpenSCAD.  They pop off because I used a thicker material on hand that doesn't require the stiffener.  Openoffice Draw is an alternative.  Automating generation of these is not worth the effort it would take, especially when it takes about 5 seconds to import the SVG and print.  

Best of luck, thanks for the great work on this.

**Comment by nikkelj** [comment]
The point is field expediency - add some instruction on how to do this in garage mode.  Paper template or puzzle jig.  Dremel tool w/ cutting wheel to cut.  I don't have a CNC laser cutter, but produced 5 in a day doing this.

**Pull request closed without merging**
