### PR TITLE
Patrick Gunderson's modifications to the Maker Nexus mod:

### PR DESCRIPTION
**Pull request by gunderson**
Goals: Make model easier to print and prepare it for resin casting.

* The headband has been refined to be able to print inverted to slightly reduce material use and increase likelihood of a clean print.
* The width of the headband has been optimized to print with 3 perimeters and no infill. It prints successfully with 2 perimeters and no infill but is not as durable.
* The headband now has a slight draft to make it easier to demold from the silicone casting.
* New, simpler supports were added to the Fusion 360 file for the vertically centered pins.
* Stacked headbands were added to the fusion 360 file.
* Varous corners were rounded over to avoid scratching the wearer and improve print quality.
* A headband and silicone mold tray have been included with index pins to aid in the molding processs.
* All changes to the headband made in the headband component will automatic

### CODE REVIEW

**Comment by gunderson** [comment]
I haven't tested the silicone mold yet, supplies will arrive next week.

**Comment by esb7** [comment]
What is the headband width set to?  We currently have two different profiles that we print with that have different extrusion widths.  The single high profile uses .6mm external perimeters and .5mm perimeters (.3mm layer height).  The stacked / high speed profile uses .55mm for all perimeters (.25mm layer height).  And the profile I've been experimenting with for a .6mm nozzle uses .7mm perimeters (.4mm layer height).  

Also, be aware that there is some overlap between each.  The formula for the spacing is:

spacing = extrusion_width - layer_height * (1 - PI/4)

So the total wall width ends up being:

total_width = extrusion_width + (num_paths * (extrusion_width - (layer_height * (1 - PI/4))))

When I've done designs in the past where I wanted to optimize for a specific profile, that worked to produce an integral number of perimeters with no gap fill.

An extra bit of gap fill isn't the end of the world, but we should see if there's a wall width that works well for all.  Alternatively we could have separate, derivative models for each profile, each with a custom wall width.  That same approach would let us keep the divot for stacks and lose it for upside down single high prints.  We're currently producing 4 different stacks, so I'm not sure we want to do the stacking in fusion.

**Comment by esb7** [comment]
Eliminating the divot may cause the stacked versions to bond together more strongly.  At least it will change the characteristic of the bond between the two and may require folks to re-calibrate their temperatures.

The supports won't likely print reliably with just a single line and might bond to the side of the headband in some cases.  Additionally, I don't think you'll get a clean print from the bottom of the pins as well.  You effectively have a direction change in midair (its an arc, but still a potential problem).  It may just be easier to keep processing the stacks in openscad and add the supports there.

**Comment by esb7** [comment]
I did have a question about how the multiple components are configured in the Fusion 360 doc.  Is there a single, master headband component / body that the others effectively inherit?  Or do each have their own copy?  It looks like the original headband body was copy/pasted into the different components.  Does Fusion 360 carry changes to the original into the derivatives with that use?  I think so, but am not 100% sure.  I want to make sure we can change things easily in the future (i.e. change the original and all derivative components get the change).

**Comment by gunderson** [comment]
Thanks for those notes. I'm going to close this for now and address them here:

The single line support prints very nicely on my CR10. I was running into issues with the circular supports being inconsistently bonded to the headband below the pins. I thought that was a design feature and I built these supports with the intent of being loosely bonded to the headband as their cross-directional support. I think I'm going to redesign the pins to be pointing slightly upward to remove the need for the supports altogether.

I use cura so multiple extrusion widths is a new concept for me. I had designed for all extrusion to be from a 0,4mm (it's what came installed on my printer, and I thought was pretty standard?) and made the walls 2.4mm, 3 perimeters. on either side. With a 0.6mm nozzle, you could reduce to 2 perimeters for the same wall-size (factors of 12 are awesome!).

In the fusion doc, there is a master component, from which the others are copies. Modifying the timeline of that component, automatically updates the copies. I'll label it better in the next version I submit. Presently it's labeled "Nexusized Thin Prusa RC2" as inherited from the adafruit version.

I've got a **much** better design in-mind for the mold and I'll have that integrated in the next version. I'm also going to attempt a direct-print mold that can be cast into directly.

Did I hit everything?

**Not in this pull request:**

Another optimization I am considering is an alternate pin layout. Laser cutting is fine for high-end production, but a cheaper solution for folks w/o access to a laser cutter might be to start with a standard letter-sized transparency (or laminating film, etc..) and to use misuse a standard 3-hole punch across the narrow side of the page instead of the long side. If the page is inserted shortways, aligned to the guide, punched. then flipped and punched again (so all 4 holes are along the same edge) it should give 4 unevenly spaced, but symmetrical holes. I think I have a punch in a closet somewhere so I'll try it out before committing the design.

**Comment by esb7** [comment]
Its probably best to discuss this on the Slack before making a bunch of model changes.  At the moment, we have some changes to revert from the model, so it will be changing (and unfortunately Fusion 360 model files don't handle forks / merges very well).

Any fundamental changes to the model probably should be discussed with Eric Hess and the folks on the channel as they are familiar with the requirements / requests we're getting from the various medical institutions.

The latest 1.6 version (which is being revoked for other reasons) has a better support structure.  It comes away super cleanly.  Your supports might have varying issues depending on the model orientation on the bed.  If they are parallel to the bed movement (y axis), they'll probably stand up better than if they're perpendicular to that axis.

- Eric

**Comment by esb7** [comment]
I should add that its great that we can have a master component like you've described.  Do you know if derivative components can customize the parameters?  That would be ideal as we can have the master baseline with appropriate values parameterized that separate derived components can customize.

BTW: Conversations like this would be good to have on the #covid-faceshield-r-and-d slack channel.

- Eric

**Pull request closed without merging**
